colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = false

[header]
  layout = "fixed"

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = false
  showMoreLink = false

[article]
  showDate = false
  showViews = false
  showLikes = false
  showAuthor = false
  showBreadcrumbs = false
  showReadingTime = false
  showTableOfContents = false
  showTaxonomies = false
  showWordCount = false

